version: '3.8'

services:
  arambyeol:
    build: .
    volumes:
      - .:/app/
      - /log/:/app/log/
    environment:
      - VIRTUAL_HOST=arambyeol.kro.kr  # 도메인 연결을 위한 환경 변수 설정
    networks:
      - reverse-proxy_proxy  # nginx-proxy 네트워크와 연결

networks:
  reverse-proxy_proxy:
    external: true